OLLAMA_API_BASE = "http://localhost:11434"
OLLAMA_OPENAI_BASE_URL = f"{OLLAMA_API_BASE}/v1"

LITELLM_BASE_URL = "http://localhost:4000"
LITELLM_OPENAI_BASE_URL = f"{LITELLM_BASE_URL}"
LITELLM_API_KEY = "anything"

DEFAULT_LOCAL_MODEL = "phi3"
DEFAULT_ROUTED_MODEL = "local-phi3"
